language: java
jdk: oraclejdk8


cache:
  directories:
  - $HOME/.m2

#script:
 # - bash <(curl -s https://codecov.io/bash)
  
  
# safelist
branches:
  only:
  - master
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "notepad-1.0.0.jar"
  skip_cleanup: true