language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
deploy:
  provider: heroku
  api_key:
    secure: 89d76e53-1f8f-4249-87ab-df0db961b3c7
app: notepad-app-travis
on:
      repo: altayeb1980/notepad
      branch: master  