language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE notepad;CREATE TABLE notepad.note (id INTEGER NOT NULL AUTO_INCREMENT,title VARCHAR(255) NOT NULL,content VARCHAR(255) NOT NULL,PRIMARY KEY (id));'

script:
  - mvn verify
  
after_success:
- pwd
- mkdir $HOME/buildApp/
- ls -l
- cd $HOME/buildApp/
- pwd
- ls -l
- git config --global user.email "loay.saada@gmail.com"
- git config --global user.name "Altayeb Saadeh"
- git clone --depth=50 --branch=master https://github.com/altayeb1980/notepad.git
- cd notepad
- ls -l
- cp -r /home/travis/build/altayeb1980/notepad/target/notepad-1.0.0.jar $HOME/buildApp/notepad
- ls -l
- git add .
- git remote rm origin
- git remote add origin https://$GITHUB_TOKEN@github.com/altayeb1980/notepad.git
- git add .
- git commit -m "Travis Build $TRAVIS_BUILD_NUMBER pushed"
- git push -fq origin master