language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE notepad;CREATE TABLE notepad.note (id INTEGER NOT NULL AUTO_INCREMENT,title VARCHAR(255) NOT NULL,content VARCHAR(255) NOT NULL,PRIMARY KEY (id));'

script:
  - mvn verify